r"""Generate the LaTeX that places panels exactly where the layout says.

The snippet uses only ``graphicx`` and the kernel ``picture`` environment with
``\unitlength=1mm``. Panels are included *without* width/height options, i.e. at scale
1.0, so fonts keep their true point size and a wrongly-sized panel is visible rather
than silently stretched.

Usage in the manuscript::

    \begin{figure}
      \centering
      \input{figures/fig1/fig1.tex}
      \caption{...}
    \end{figure}

Panel letters carry their own font commands, built from the layout's ``panel_label`` style (size,
weight, and ``latex_font``), so the file defines nothing: change the letters in the layout and
rebuild.

They are stamped with ``\put`` at the millimetre the layout gives, over the panel's own margin,
so they take no space of their own -- unlike ``subcaption``/``subfigure``, which add a line
under each panel and would make the assembled figure taller than the layout says.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path, PurePosixPath

from .layout import Layout
from .style import label_text


def _fmt(value: float) -> str:
    return f"{value:.2f}"


def figure_tex(layout: Layout, graphics_prefix: str = "panels/", labels: bool = True) -> str:
    r"""LaTeX source of the figure body (no ``figure`` environment, no caption).

    What comes out is meant to be read by whoever opens it in Overleaf: a picture box of the
    figure's size, one ``\includegraphics`` per panel, one ``\makebox`` per letter. The only
    letters carry their font on themselves, so nothing is defined and nothing is loaded.
    """
    label = layout.style["panel_label"]
    weight = r"\bfseries" if label["weight"] == "bold" else ""
    size = float(label["size"])
    family = str(label.get("latex_font") or r"\sffamily")
    # The font commands go on each letter rather than into a macro: the file then defines
    # nothing at all, and can be read, edited and pasted without knowing what plotplate is.
    font = f"\\fontsize{{{size:g}pt}}{{{size:g}pt}}\\selectfont{family}{weight}"
    source = layout.path.name if layout.path else "a layout mapping"
    lines = [
        f"% The panels of {layout.name}, placed. Generated by plotplate from {source}:",
        "% `plotplate build` rewrites this file, so put the caption, the label and the figure",
        f"% placement in {layout.name}-figure.tex (or in the manuscript), not here.",
        "% Requires \\usepackage{graphicx}. Panels are included at natural size (scale 1.0).",
        "{\\setlength{\\unitlength}{1mm}%",
        f"\\begin{{picture}}({_fmt(layout.width)},{_fmt(layout.height)})%",
    ]
    for name, spec in layout.panels.items():
        path = PurePosixPath(graphics_prefix) / f"{name}.pdf" if graphics_prefix else f"{name}.pdf"
        # picture coordinates: origin bottom-left; an image's reference point is its bottom-left.
        said = (
            name if not spec.label or spec.label.lower() == name.lower() else f"{name} ({spec.label})"
        )
        lines.append(
            f"\\put({_fmt(spec.box.x)},{_fmt(layout.height - spec.box.bottom)})"
            f"{{\\includegraphics{{{path}}}}}% panel {said}"
        )
    if labels:
        for spec in layout.panels.values():
            if not spec.label:
                continue
            x = spec.box.x + spec.label_offset[0]
            y = layout.height - (spec.box.y + spec.label_offset[1])
            text = label_text(layout.style, spec.label)
            lines.append(f"\\put({_fmt(x)},{_fmt(y)}){{\\makebox(0,0)[lt]{{{{{font} {text}}}}}}}%")
    lines += ["\\end{picture}}%", ""]
    return "\n".join(lines)


def write_figure_tex(
    layout: Layout,
    out: str | Path | None = None,
    graphics_prefix: str = "panels/",
    labels: bool = True,
) -> Path:
    """Write the snippet to ``out`` (default ``<layout dir>/<name>.tex``)."""
    target = Path(out) if out is not None else layout.output_dir / f"{layout.name}.tex"
    target.write_text(figure_tex(layout, graphics_prefix, labels), encoding="utf-8")
    return target


def write_figure_scaffold(
    layout: Layout,
    out: str | Path | None = None,
    graphics_prefix: str | None = None,
    force: bool = False,
) -> Path:
    r"""Write ``<name>-figure.tex``: the figure as the manuscript sees it, for the author to edit.

    This is the half of the output that is *not* generated material. It holds the ``figure``
    environment, the placement, the caption and the label -- the parts that belong to the text --
    and it includes the generated file, which holds the panels. The manuscript then needs one
    line per figure::

        \input{figures/figure_7/figure_7-figure.tex}

    It is written once and never again: ``plotplate build`` rewrites the panels beside it and
    leaves this file alone, so a caption written here survives every rebuild. ``plotplate latex``
    copies *this* file into the upload folder, with only the included path changed, so the
    caption travels with it. ``force`` writes a fresh one, which is how to get the scaffold back
    after deleting it.

    ``graphics_prefix`` is where the included file sits *as the manuscript sees it*. Left out,
    it is the path from this file to the output folder -- nothing when a build writes beside the
    layout, ``output/`` when it writes into ``output_dir`` -- so the file compiles from the
    figure folder. The copy ``plotplate latex`` writes carries the Overleaf path instead.
    """
    import os

    target = Path(out) if out is not None else layout.base_dir / f"{layout.name}-figure.tex"
    if target.exists() and not force:
        return target
    if graphics_prefix is None:
        relative = os.path.relpath(layout.output_dir, layout.base_dir)
        graphics_prefix = "" if relative == "." else f"{relative}/"
    body = f"{graphics_prefix}{layout.name}.tex" if graphics_prefix else f"{layout.name}.tex"
    anchor = f"fig:{layout.name}"
    lines = [
        f"% {layout.name}: this file is yours. Edit the caption, the label, the",
        "% placement ([t], [h!], ...), or wrap it in a starred figure* for a wide one.",
        "% plotplate never overwrites it; it rewrites the panels in the file included below.",
        "% The path below is relative to whatever LaTeX compiles: adjust it when this file is",
        "% included from a manuscript in another folder (`plotplate latex` writes it ready).",
        "\\begin{figure}[tbp]",
        "  \\centering",
        f"  \\input{{{body}}}%",
        "  \\caption{...}",
        f"  \\label{{{anchor}}}",
        f"  % To reference one panel (\\ref{{{anchor}a}} prints 7a), load subcaption in the",
        "  % preamble and uncomment the lines below. They print nothing and take no space.",
    ]
    lines += [
        f"  % \\begin{{subfigure}}[t]{{0pt}}\\phantomsubcaption"
        f"\\label{{{anchor}{spec.label.lower()}}}\\end{{subfigure}}%  panel {name}"
        for name, spec in layout.panels.items()
        if spec.label
    ]
    lines += ["\\end{figure}", ""]
    target.write_text("\n".join(lines), encoding="utf-8")
    return target


def bundle(layout: Layout, out_dir: str | Path, graphics_prefix: str | None = None) -> Path:
    r"""Fill ``out_dir`` with what a manuscript needs: the panel PDFs and the two ``.tex`` files.

    ``\input{<name>.tex}`` is what places the panels, which is what keeps them at scale 1.0 and
    the letters where the layout puts them. ``<name>-figure.tex`` is **copied** from the one
    beside the layout, with only the included path rewritten, so the caption written there is
    the caption that gets uploaded.

    Args:
        layout: the figure layout.
        out_dir: destination folder (created). Upload its content as-is.
        graphics_prefix: path of the panels as seen from the Overleaf project root,
            default ``figures/<name>/``, matching an upload of ``out_dir`` there.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    prefix = graphics_prefix if graphics_prefix is not None else f"figures/{layout.name}/"
    missing = []
    for name in layout.panels:
        pdf = layout.panels_dir / f"{name}.pdf"
        if pdf.exists():
            shutil.copy2(pdf, out_dir / pdf.name)
        else:
            missing.append(name)
    if missing:
        raise FileNotFoundError(f"Panels without PDF: {missing}; run their notebooks first")
    _copy_scaffold(layout, out_dir / f"{layout.name}-figure.tex", prefix)
    return write_figure_tex(layout, out_dir / f"{layout.name}.tex", graphics_prefix=prefix)


def _copy_scaffold(layout: Layout, target: Path, prefix: str) -> Path:
    r"""Carry the author's ``<name>-figure.tex`` across, pointing at the uploaded panels file.

    Only the ``\input{...<name>.tex}`` line changes. Everything else -- the caption, the label,
    the placement, whatever was added by hand -- is the author's and is copied as it stands. If
    there is no such file yet (nothing was built), a fresh scaffold is written instead.
    """
    source = layout.base_dir / f"{layout.name}-figure.tex"
    if not source.exists():
        return write_figure_scaffold(layout, target, graphics_prefix=prefix, force=True)
    pattern = re.compile(r"\\input\{[^}]*" + re.escape(layout.name) + r"\.tex\}")
    wanted = f"\\input{{{prefix}{layout.name}.tex}}"
    text, count = pattern.subn(lambda _: wanted, source.read_text(encoding="utf-8"))
    if not count:  # the author rewrote the include themselves; leave it alone
        text = source.read_text(encoding="utf-8")
    target.write_text(text, encoding="utf-8")
    return target


def standalone_document(layout: Layout, graphics_prefix: str = "panels/", labels: bool = True) -> str:
    """A compilable document whose page is exactly the figure (``standalone`` class)."""
    return "\n".join(
        [
            "\\documentclass[border=0pt]{standalone}",
            "\\usepackage{graphicx}",
            "\\begin{document}",
            figure_tex(layout, graphics_prefix, labels),
            "\\end{document}",
            "",
        ]
    )
