r"""Generate the LaTeX that places panels exactly where the layout says.

The snippet uses only ``graphicx`` and the kernel ``picture`` environment with
``\unitlength=1mm``. Panels are included *without* width/height options, i.e. at scale
1.0, so fonts keep their true point size and a wrongly-sized panel is visible rather
than silently stretched.

Usage in the manuscript::

    \begin{figure}
      \centering
      \input{figures/fig1/fig1.tex}
      \caption{...}
    \end{figure}

Panel letters use ``\plotplatePanelLabel``, defined with ``\providecommand``: define your own
version in the preamble to change their font.
"""

from __future__ import annotations

import shutil
from pathlib import Path, PurePosixPath

from .layout import Layout


def _fmt(value: float) -> str:
    return f"{value:.2f}"


def figure_tex(layout: Layout, graphics_prefix: str = "panels/", labels: bool = True) -> str:
    """LaTeX source of the figure body (no ``figure`` environment, no caption)."""
    label = layout.style["panel_label"]
    weight = r"\bfseries" if label["weight"] == "bold" else ""
    size = float(label["size"])
    source = layout.path.name if layout.path else "a layout mapping"
    lines = [
        f"% Generated by plotplate from {source} ({layout.name}). Do not edit by hand.",
        "% Requires \\usepackage{graphicx}. Panels are included at natural size (scale 1.0).",
        "\\providecommand{\\plotplatePanelLabel}[1]{{\\fontsize{"
        + f"{size:g}pt"
        + "}{"
        + f"{size:g}pt"
        + "}\\selectfont\\sffamily"
        + weight
        + " #1}}%",
        "{\\setlength{\\unitlength}{1mm}%",
        f"\\begin{{picture}}({_fmt(layout.width)},{_fmt(layout.height)})%",
    ]
    for name, spec in layout.panels.items():
        path = PurePosixPath(graphics_prefix) / f"{name}.pdf" if graphics_prefix else f"{name}.pdf"
        # picture coordinates: origin bottom-left; an image's reference point is its bottom-left.
        lines.append(
            f"\\put({_fmt(spec.box.x)},{_fmt(layout.height - spec.box.bottom)})"
            f"{{\\includegraphics{{{path}}}}}% panel {name}"
        )
    if labels:
        for spec in layout.panels.values():
            if not spec.label:
                continue
            x = spec.box.x + spec.label_offset[0]
            y = layout.height - (spec.box.y + spec.label_offset[1])
            lines.append(
                f"\\put({_fmt(x)},{_fmt(y)}){{\\makebox(0,0)[lt]{{\\plotplatePanelLabel{{{spec.label}}}}}}}%"
            )
    lines += ["\\end{picture}}%", ""]
    return "\n".join(lines)


def write_figure_tex(
    layout: Layout,
    out: str | Path | None = None,
    graphics_prefix: str = "panels/",
    labels: bool = True,
) -> Path:
    """Write the snippet to ``out`` (default ``<layout dir>/<name>.tex``)."""
    target = Path(out) if out is not None else layout.base_dir / f"{layout.name}.tex"
    target.write_text(figure_tex(layout, graphics_prefix, labels), encoding="utf-8")
    return target


def bundle(layout: Layout, out_dir: str | Path, graphics_prefix: str | None = None) -> Path:
    """Copy ``<name>.tex`` and the panel PDFs into ``out_dir`` for upload to Overleaf.

    Args:
        layout: the figure layout.
        out_dir: destination folder (created). Upload its content as-is.
        graphics_prefix: path of the panels as seen from the Overleaf project root,
            default ``figures/<name>/``, matching an upload of ``out_dir`` there.
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    prefix = graphics_prefix if graphics_prefix is not None else f"figures/{layout.name}/"
    missing = []
    for name in layout.panels:
        pdf = layout.panels_dir / f"{name}.pdf"
        if pdf.exists():
            shutil.copy2(pdf, out_dir / pdf.name)
        else:
            missing.append(name)
    if missing:
        raise FileNotFoundError(f"Panels without PDF: {missing}; run their notebooks first")
    return write_figure_tex(layout, out_dir / f"{layout.name}.tex", graphics_prefix=prefix)


def standalone_document(layout: Layout, graphics_prefix: str = "panels/", labels: bool = True) -> str:
    """A compilable document whose page is exactly the figure (``standalone`` class)."""
    return "\n".join(
        [
            "\\documentclass[border=0pt]{standalone}",
            "\\usepackage{graphicx}",
            "\\begin{document}",
            figure_tex(layout, graphics_prefix, labels),
            "\\end{document}",
            "",
        ]
    )
